apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: memory-game-app
  namespace: openshift-gitops
spec:
  destination:
    namespace: memory-game
    server: https://kubernetes.default.svc 
  project: default 
  source: 
    path: memory-game/application-mainfest
    repoURL: https://github.com/ksingh7/argocd-openshift
    targetRevision: main
  syncPolicy: 
    automated:
      prune: true
      selfHeal: false
    syncOptions:
    - CreateNamespace=true